spring.application.name=topo
spring.main.log-startup-info=false



# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/topo
spring.datasource.username=topo
spring.datasource.password=topo
spring.jpa.show-sql=true

# JPA (schema is managed by Flyway, so only validate)
spring.jpa.hibernate.ddl-auto=validate

# DB Migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration